apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: loan-management
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: loan_management
  MYSQL_USER: loanuser
  MYSQL_PASSWORD: loanpassword
