apiVersion: v1
kind: Service

metadata:
  name: loan-management-service
  namespace: loan-management

spec:
  selector:
    app: loan-management-app

  ports:
  - port: 80
    targetPort: 8080

  type: LoadBalancer
